name: Deploy Blazor App to Azure Static Web Apps

on:
  push:
    branches:
      - main  # ou la branche principale que vous utilisez

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor App
        run: dotnet publish -c Release -o release

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatique
          action: "upload"
          app_location: "release/wwwroot"
          output_location: ""  # vide car on a déjà buildé nous-mêmes
